
package com.saber.simple_soap.soap.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2023-03-27T13:23:59.665+03:30
 * Generated source version: 3.5.3
 *
 */
public final class HelloService_HelloServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://soap.simple_soap.saber.com/", "HelloService");

    private HelloService_HelloServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloServiceProxy.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        HelloServiceProxy ss = new HelloServiceProxy(wsdlURL, SERVICE_NAME);
        HelloService port = ss.getHelloServicePort();

        {
        System.out.println("Invoking sayHello...");
        java.lang.String _sayHello_firstName = "";
        java.lang.String _sayHello_lastName = "";
        com.saber.simple_soap.soap.client.MessageResponse _sayHello__return = port.sayHello(_sayHello_firstName, _sayHello_lastName);
        System.out.println("sayHello.result=" + _sayHello__return);


        }
        {
        System.out.println("Invoking sayBye...");
        java.lang.String _sayBye_firstName = "";
        java.lang.String _sayBye_lastName = "";
        com.saber.simple_soap.soap.client.MessageResponse _sayBye__return = port.sayBye(_sayBye_firstName, _sayBye_lastName);
        System.out.println("sayBye.result=" + _sayBye__return);


        }

        System.exit(0);
    }

}
